import type { IndustryDataset, StyleStrand } from './types'

const tattooStyles: StyleStrand[] = [
  {
    id: 'americana-traditional',
    label: 'Americana Traditional',
    tagline: 'Bold lines, limited palette, eternal',
    description:
      'Sailor Jerry, Bert Grimm, Ed Hardy lineage. Heavy black outlines, a tight palette of red/yellow/green/black, classic motifs (eagles, daggers, panthers, pin-ups). Built to age well across 40+ years on skin.',
    origin: 1900,
    ancestors: [],
    curve: [
      { year: 1920, value: 35 },
      { year: 1945, value: 78 },
      { year: 1960, value: 55 },
      { year: 1975, value: 30 },
      { year: 1990, value: 38 },
      { year: 2005, value: 70 },
      { year: 2015, value: 84 },
      { year: 2022, value: 88 },
      { year: 2025, value: 82 },
    ],
    signals: ['nostalgia', 'craft revival', 'analog backlash', 'durability bias'],
    tags: ['bold', 'iconographic', 'colored', 'heritage'],
    pioneers: ['Sailor Jerry Collins', 'Bert Grimm', 'Ed Hardy'],
  },
  {
    id: 'fine-line',
    label: 'Fine Line / Single Needle',
    tagline: 'Whisper-thin lines, micro detail',
    description:
      'Single-needle origins in 1970s East LA prison and Chicano scenes (Jack Rudy, Freddy Negrete, Charlie Cartwright at Good Time Charlie\'s). Resurfaced as celebrity-friendly micro tattoos around 2005, then exploded post-2017 with Dr. Woo and Instagram-native artists.',
    origin: 1970,
    parentId: 'black-grey-chicano',
    ancestors: ['black-grey-chicano'],
    curve: [
      { year: 1975, value: 42 },
      { year: 1985, value: 55 },
      { year: 1995, value: 28 },
      { year: 2005, value: 48 },
      { year: 2015, value: 70 },
      { year: 2020, value: 88 },
      { year: 2024, value: 95 },
      { year: 2025, value: 96 },
    ],
    signals: ['minimalism', 'instagram-native', 'celebrity adoption', 'micro detail'],
    tags: ['delicate', 'minimal', 'monochrome', 'modern'],
    pioneers: ['Jack Rudy', 'Freddy Negrete', 'Dr. Woo', 'JonBoy'],
  },
  {
    id: 'black-grey-chicano',
    label: 'Black & Grey Chicano',
    tagline: 'Photorealism in soft greys, smoky shading',
    description:
      'Born in 1970s LA from prison-yard single-needle work. Religious iconography, lowrider culture, smoke and roses. Bridge between fine line and full realism.',
    origin: 1970,
    ancestors: [],
    curve: [
      { year: 1975, value: 38 },
      { year: 1990, value: 65 },
      { year: 2005, value: 78 },
      { year: 2015, value: 68 },
      { year: 2022, value: 60 },
      { year: 2025, value: 64 },
    ],
    signals: ['heritage', 'realism', 'storytelling'],
    tags: ['monochrome', 'smoky', 'cultural'],
    pioneers: ['Mister Cartoon', 'Chuey Quintanar'],
  },
  {
    id: 'tribal',
    label: 'Tribal / Polynesian',
    tagline: 'Solid black geometry rooted in Oceania',
    description:
      'True Polynesian (Tatau, Marquesan, Samoan) is millennia old. Western "tribal" shorthand peaked in the 1990s post-grunge. Authentic Polynesian work has steadily climbed since 2010 alongside indigenous reclamation.',
    origin: 1980,
    ancestors: [],
    curve: [
      { year: 1990, value: 60 },
      { year: 1998, value: 92 },
      { year: 2005, value: 70 },
      { year: 2012, value: 30 },
      { year: 2018, value: 38 },
      { year: 2024, value: 52 },
      { year: 2025, value: 56 },
    ],
    signals: ['cultural reclamation', 'indigenous craft', 'bold shapes'],
    tags: ['blackwork', 'cultural', 'pattern'],
  },
  {
    id: 'realism',
    label: 'Photo Realism',
    tagline: 'Skin as a print, every pore rendered',
    description:
      'Emerged in the late 1990s with rotary machines and refined cartridges; matured around 2010 with hyperrealism. High-effort, high-skill style that competes with portraiture and oil painting.',
    origin: 1995,
    parentId: 'black-grey-chicano',
    ancestors: ['black-grey-chicano'],
    curve: [
      { year: 2000, value: 35 },
      { year: 2010, value: 70 },
      { year: 2017, value: 86 },
      { year: 2022, value: 78 },
      { year: 2025, value: 70 },
    ],
    signals: ['technical mastery', 'portrait commission', 'memorial'],
    tags: ['detailed', 'modern', 'monochrome'],
    pioneers: ['Nikko Hurtado', 'Bob Tyrrell'],
  },
  {
    id: 'hyperrealism',
    label: 'Hyperrealism',
    tagline: 'Skin-as-photography, every micro-shadow',
    description:
      'A 2010s extreme of realism — pushed by competition culture and Instagram zoom. Long sittings, color charts, airbrush-style gradients. Ages well only with a master; technically punishing.',
    origin: 2008,
    parentId: 'realism',
    ancestors: ['realism', 'black-grey-chicano'],
    curve: [
      { year: 2010, value: 35 },
      { year: 2016, value: 78 },
      { year: 2020, value: 82 },
      { year: 2024, value: 70 },
      { year: 2025, value: 64 },
    ],
    signals: ['competition culture', 'long sittings', 'technical mastery'],
    tags: ['detailed', 'monochrome', 'modern'],
  },
  {
    id: 'mandala',
    label: 'Mandala',
    tagline: 'Symmetric circular sacred geometry',
    description:
      'Subset of geometric/blackwork built on radial symmetry, rooted in Hindu/Buddhist iconography. Surged with the 2014 sacred-geometry wave; durable as a center-of-piece motif inside larger ornamental sleeves.',
    origin: 2012,
    parentId: 'geometric',
    ancestors: ['geometric', 'blackwork', 'dotwork'],
    curve: [
      { year: 2014, value: 55 },
      { year: 2018, value: 72 },
      { year: 2022, value: 60 },
      { year: 2025, value: 56 },
    ],
    signals: ['symmetry', 'spiritual', 'craft'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
  {
    id: 'micro-realism',
    label: 'Micro Realism',
    tagline: 'Realism shrunk to a coin',
    description:
      'Korean and Spanish scenes (Inal Bersekov, Eva Krbdk) compressed full realism into 2-inch panels with fine line outlines. Defined the late 2010s Instagram aesthetic of pets, flowers and tiny still lifes.',
    origin: 2014,
    parentId: 'fine-line',
    ancestors: ['fine-line', 'realism'],
    curve: [
      { year: 2016, value: 30 },
      { year: 2019, value: 65 },
      { year: 2022, value: 88 },
      { year: 2025, value: 86 },
    ],
    signals: ['instagram-native', 'collectible', 'small format'],
    tags: ['minimal', 'detailed', 'modern'],
    pioneers: ['Inal Bersekov', 'Eva Krbdk'],
  },
  {
    id: 'neo-traditional',
    label: 'Neo-Traditional',
    tagline: 'Traditional bones, painterly skin',
    description:
      'Expands Americana with deeper palettes, soft gradients, art nouveau line weights. Late-2000s wave (Jeff Gogue, Russ Abbott) into a steady mainstream presence.',
    origin: 2005,
    parentId: 'americana-traditional',
    ancestors: ['americana-traditional'],
    curve: [
      { year: 2008, value: 45 },
      { year: 2015, value: 78 },
      { year: 2020, value: 80 },
      { year: 2025, value: 72 },
    ],
    signals: ['painterly', 'palette expansion', 'illustrative'],
    tags: ['colored', 'illustrative', 'modern'],
  },
  {
    id: 'new-school',
    label: 'New School',
    tagline: 'Cartoonish, bulging, candy-colored',
    description:
      'Mid-1990s Skribblz / Marcus Pacheco era. Exaggerated proportions, 3D rendering, graffiti DNA. Faded after 2005, low-key revival forming in collaboration with cyber sigilism artists.',
    origin: 1990,
    parentId: 'americana-traditional',
    ancestors: ['americana-traditional'],
    curve: [
      { year: 1995, value: 55 },
      { year: 2002, value: 78 },
      { year: 2010, value: 35 },
      { year: 2020, value: 18 },
      { year: 2025, value: 26 },
    ],
    signals: ['cartoon revival', 'graffiti', 'maximalist color'],
    tags: ['colored', 'illustrative', 'maximal'],
  },
  {
    id: 'japanese-irezumi',
    label: 'Japanese Irezumi',
    tagline: 'Bodysuits, koi, dragons, wind bars',
    description:
      'Edo-period roots. Western adoption surged in the 1980s through Horiyoshi III and Don Ed Hardy. Steady, slow-burning popularity; never a fad, never the lead.',
    origin: 1700,
    ancestors: [],
    curve: [
      { year: 1985, value: 55 },
      { year: 2000, value: 60 },
      { year: 2015, value: 65 },
      { year: 2025, value: 60 },
    ],
    signals: ['heritage', 'large scale', 'narrative'],
    tags: ['colored', 'heritage', 'pattern'],
    pioneers: ['Horiyoshi III'],
  },
  {
    id: 'blackwork',
    label: 'Blackwork',
    tagline: 'Saturated black geometry and ornament',
    description:
      'Distinct from tribal; descends from European etching, mehndi, sacred geometry. Strongly tied to ornamental, mandala and dotwork. Steady riser since 2012.',
    origin: 2008,
    parentId: 'tribal',
    ancestors: ['tribal'],
    curve: [
      { year: 2012, value: 40 },
      { year: 2018, value: 70 },
      { year: 2022, value: 78 },
      { year: 2025, value: 74 },
    ],
    signals: ['ornament', 'sacred geometry', 'monochrome maximalism'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
  {
    id: 'dotwork',
    label: 'Dotwork / Stippling',
    tagline: 'Tonal shading made of dots',
    description:
      'Xed LeHead-era dotwork from the 1990s Berlin scene. Used as a shading vocabulary inside ornamental and geometric. Rarely the headline, often the substrate.',
    origin: 1992,
    ancestors: [],
    curve: [
      { year: 1998, value: 30 },
      { year: 2010, value: 55 },
      { year: 2018, value: 70 },
      { year: 2025, value: 64 },
    ],
    signals: ['craft', 'patience', 'texture'],
    tags: ['blackwork', 'pattern'],
  },
  {
    id: 'geometric',
    label: 'Geometric',
    tagline: 'Sacred geometry, ruler-true lines',
    description:
      'Mandala and sacred geometry boom around 2013, often paired with dotwork or fine line. Now a substyle backbone for ornamental and cyber sigilism.',
    origin: 2010,
    parentId: 'blackwork',
    ancestors: ['dotwork', 'blackwork'],
    curve: [
      { year: 2013, value: 55 },
      { year: 2018, value: 78 },
      { year: 2022, value: 70 },
      { year: 2025, value: 62 },
    ],
    signals: ['symmetry', 'meditation', 'craft'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
  {
    id: 'watercolor',
    label: 'Watercolor',
    tagline: 'Splashes, drips, no outlines',
    description:
      'Early-2010s viral aesthetic (Ondrash). Aged poorly; popularity peaked then fell as collectors saw 5-year results. Lives on as an accent inside neo-traditional.',
    origin: 2010,
    parentId: 'neo-traditional',
    ancestors: ['neo-traditional'],
    curve: [
      { year: 2013, value: 70 },
      { year: 2017, value: 78 },
      { year: 2021, value: 45 },
      { year: 2025, value: 28 },
    ],
    signals: ['painterly', 'no outline', 'pinterest era'],
    tags: ['colored', 'illustrative'],
  },
  {
    id: 'trash-polka',
    label: 'Trash Polka',
    tagline: 'Red and black collage chaos',
    description:
      'Buena Vista Tattoo Club, Germany. Early 2010s peak. Photorealism + brushstrokes + typographic noise.',
    origin: 2008,
    parentId: 'realism',
    ancestors: ['realism'],
    curve: [
      { year: 2012, value: 60 },
      { year: 2016, value: 70 },
      { year: 2022, value: 32 },
      { year: 2025, value: 24 },
    ],
    signals: ['collage', 'editorial', 'bold contrast'],
    tags: ['colored', 'maximal', 'modern'],
  },
  {
    id: 'cyber-sigilism',
    label: 'Cyber Sigilism',
    tagline: 'Y2K chrome meets occult linework',
    description:
      'A 2020+ TikTok-fueled fusion: tribal silhouettes, fine line execution, sigil and Y2K typography. Compresses the canonical 22-year cycle to ~4 years end-to-end.',
    origin: 2020,
    parentId: 'blackwork',
    ancestors: ['fine-line', 'tribal', 'blackwork'],
    curve: [
      { year: 2021, value: 28 },
      { year: 2023, value: 70 },
      { year: 2025, value: 88 },
    ],
    signals: ['tiktok-native', 'y2k revival', 'gen-z occult', 'fast cycle'],
    tags: ['blackwork', 'pattern', 'modern', 'fusion'],
  },
  {
    id: 'illustrative-anime',
    label: 'Illustrative / Anime',
    tagline: 'Manga lineart, cel shading',
    description:
      'Driven by post-2018 anime mainstreaming. Big in Asia and Latin America. Often colored, often single-panel comp.',
    origin: 2015,
    parentId: 'new-school',
    ancestors: ['new-school', 'neo-traditional'],
    curve: [
      { year: 2018, value: 40 },
      { year: 2022, value: 70 },
      { year: 2025, value: 78 },
    ],
    signals: ['fandom', 'streaming', 'illustration'],
    tags: ['colored', 'illustrative', 'modern'],
  },
  {
    id: 'ignorant-handpoke',
    label: 'Ignorant / Handpoke',
    tagline: 'Wonky lines, deliberate amateurism',
    description:
      'Fuzi Uvtpk-led 2010s scene; handpoke made it portable. Reads as anti-craft but is a craft of its own. Pairs with fine line on a single sleeve.',
    origin: 2009,
    ancestors: [],
    curve: [
      { year: 2012, value: 35 },
      { year: 2018, value: 62 },
      { year: 2022, value: 70 },
      { year: 2025, value: 64 },
    ],
    signals: ['anti-craft', 'punk', 'flash culture'],
    tags: ['minimal', 'illustrative', 'modern'],
  },
  {
    id: 'ornamental',
    label: 'Ornamental',
    tagline: 'Lace, jewelry, body-as-frame',
    description:
      'Decorative blackwork descended from mehndi and Eastern European ornament. Used as clothing-line work that follows anatomy.',
    origin: 2014,
    parentId: 'blackwork',
    ancestors: ['blackwork', 'dotwork'],
    curve: [
      { year: 2016, value: 45 },
      { year: 2020, value: 70 },
      { year: 2024, value: 80 },
      { year: 2025, value: 78 },
    ],
    signals: ['anatomical', 'craft', 'feminine maximalism'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
]

export const TATTOO_DATASET: IndustryDataset = {
  industry: {
    id: 'tattoo',
    label: 'Tattoo',
    blurb: 'Cycle window 18-25 years, compressing toward 6-10 since 2017.',
    status: 'active',
  },
  styles: tattooStyles,
  cycleNotes: [
    'Sailor Jerry Americana peaked ~1945, dipped, came back hard ~2005 and has held the lead among under-30 collectors for two decades.',
    'Fine line shows two distinct waves: 1975-1985 East LA single-needle, then a Dr. Woo / Instagram explosion 2017-now.',
    'Tribal sat dormant ~2008-2018 then re-emerged as cyber sigilism — a clear "fusion-driven" comeback rather than a faithful one.',
    'Watercolor is a textbook accelerated cycle: 7-year peak-to-trough vs the canonical 22, killed by visible aging.',
  ],
  yearRange: { start: 1900, end: 2030 },
}

export const FASHION_DATASET: IndustryDataset = {
  industry: {
    id: 'fashion',
    label: 'Fashion',
    blurb: 'Cycle window 20-25 years for silhouettes, 5-7 years for microtrends post-2010.',
    status: 'active',
  },
  styles: [
    {
      id: 'mod-60s',
      label: 'Mod (60s)',
      tagline: 'A-line minis, monochrome, geometric prints',
      description:
        'British 1960s — Mary Quant, Twiggy, Carnaby Street. Geometric prints, A-line shifts, knee-high boots. Hedi Slimane echoes ~2005, returned as a microtrend in 2024 with the "indie sleaze 2.0" wave.',
      origin: 1960,
      ancestors: [],
      curve: [
        { year: 1965, value: 92 },
        { year: 1972, value: 35 },
        { year: 1985, value: 22 },
        { year: 2005, value: 60 },
        { year: 2018, value: 32 },
        { year: 2024, value: 52 },
        { year: 2025, value: 55 },
      ],
      signals: ['silhouette', 'geometric', 'pop'],
      tags: ['silhouette', 'graphic'],
      pioneers: ['Mary Quant', 'André Courrèges', 'Twiggy'],
    },
    {
      id: 'hippie-bohemian',
      label: 'Hippie / Bohemian',
      tagline: 'Earth tones, fringe, peasant blouses, prairie',
      description:
        'Late-60s counterculture and 70s prairie. Flowy cotton, earth tones, ethnic textiles. The 2014 boho-festival wave (Coachella era) revived it; "cottagecore" 2020-22 is the descendant.',
      origin: 1967,
      ancestors: [],
      curve: [
        { year: 1971, value: 88 },
        { year: 1980, value: 28 },
        { year: 1995, value: 42 },
        { year: 2005, value: 55 },
        { year: 2014, value: 78 },
        { year: 2022, value: 60 },
        { year: 2025, value: 52 },
      ],
      signals: ['nostalgia', 'craft', 'earth tones', 'pinterest era'],
      tags: ['silhouette', 'soft', 'natural'],
    },
    {
      id: 'bell-bottoms',
      label: 'Bell Bottoms',
      tagline: 'Flared denim, hip-hugger waist',
      description:
        '1970s flared denim peak; late-1990s mainstream revival driven by Britney/JNCO; low-rise flare wave 2022-now. The classic 22-year cycle reference case.',
      origin: 1965,
      parentId: 'hippie-bohemian',
      ancestors: ['hippie-bohemian'],
      curve: [
        { year: 1972, value: 90 },
        { year: 1980, value: 25 },
        { year: 1998, value: 80 },
        { year: 2005, value: 35 },
        { year: 2018, value: 22 },
        { year: 2022, value: 68 },
        { year: 2025, value: 78 },
      ],
      signals: ['silhouette', 'denim', 'nostalgia'],
      tags: ['silhouette', 'denim'],
    },
    {
      id: 'disco-glam',
      label: 'Disco Glam',
      tagline: 'Sequins, jumpsuits, satin, Studio 54',
      description:
        '1977-79 peak; lampooned in the 80s, briefly fashionable around 2000 and again with the 2022 "Y2K disco" microtrend (Beyoncé Renaissance era).',
      origin: 1975,
      ancestors: [],
      curve: [
        { year: 1978, value: 88 },
        { year: 1985, value: 22 },
        { year: 2000, value: 48 },
        { year: 2010, value: 25 },
        { year: 2022, value: 62 },
        { year: 2025, value: 50 },
      ],
      signals: ['nightlife', 'shimmer', 'maximalism'],
      tags: ['glam', 'evening', 'maximal'],
    },
    {
      id: 'punk',
      label: 'Punk',
      tagline: 'Leather, plaid, safety pins, DIY',
      description:
        'Late-70s London (Westwood/McLaren) and NYC (Ramones). Mainstreamed via Vivienne Westwood through the 80s and 90s. Lives on as an evergreen subculture and as a recurring runway pull (Balenciaga 2022, McQueen archive references).',
      origin: 1976,
      ancestors: [],
      curve: [
        { year: 1979, value: 65 },
        { year: 1990, value: 45 },
        { year: 2005, value: 55 },
        { year: 2015, value: 40 },
        { year: 2022, value: 58 },
        { year: 2025, value: 50 },
      ],
      signals: ['anti-fashion', 'subculture', 'DIY'],
      tags: ['edgy', 'subculture'],
      pioneers: ['Vivienne Westwood', 'Malcolm McLaren'],
    },
    {
      id: 'power-suit-80s',
      label: '80s Power Suit',
      tagline: 'Shoulder pads, double-breasted, monochrome bold',
      description:
        'Reagan-era corporate power dressing. Returned 2017-19 (Mango / Zara wave), again 2022 with "office siren" / Saint Laurent silhouettes. Shoulder pads remain divisive.',
      origin: 1982,
      ancestors: [],
      curve: [
        { year: 1986, value: 86 },
        { year: 1993, value: 25 },
        { year: 2010, value: 18 },
        { year: 2018, value: 55 },
        { year: 2024, value: 48 },
        { year: 2025, value: 44 },
      ],
      signals: ['corporate', 'silhouette', 'authority'],
      tags: ['silhouette', 'tailoring', 'workwear'],
    },
    {
      id: 'preppy',
      label: 'Preppy',
      tagline: 'Polo collars, loafers, pastel layering',
      description:
        '80s Reagan-era prep (Ralph Lauren). Mid-2000s "Gossip Girl" revival. "Old money" / "tomato girl" 2023+ is the same DNA reframed.',
      origin: 1980,
      ancestors: [],
      curve: [
        { year: 1985, value: 68 },
        { year: 1995, value: 35 },
        { year: 2008, value: 65 },
        { year: 2016, value: 38 },
        { year: 2023, value: 70 },
        { year: 2025, value: 75 },
      ],
      signals: ['heritage', 'aspirational', 'classic'],
      tags: ['classic', 'tailoring'],
    },
    {
      id: 'grunge',
      label: 'Grunge',
      tagline: 'Plaid flannels, slip dresses, combat boots',
      description:
        'Seattle 1991-94 (Nirvana, Marc Jacobs for Perry Ellis). 2014-16 Hedi-at-Saint-Laurent revival. "Grunge revival" microtrend re-emerged 2022 with cyber-sigilism crossover.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 1993, value: 82 },
        { year: 1999, value: 30 },
        { year: 2014, value: 65 },
        { year: 2018, value: 40 },
        { year: 2022, value: 58 },
        { year: 2025, value: 52 },
      ],
      signals: ['anti-fashion', 'subculture', 'thrift'],
      tags: ['subculture', 'thrift', 'denim'],
    },
    {
      id: 'y2k',
      label: 'Y2K',
      tagline: 'Low-rise, butterfly motifs, baby tees, chrome',
      description:
        '1999-2003 — Britney/Aaliyah/Destiny\'s Child era. Tech-optimist chrome, butterfly motifs, low-rise denim. The flagship case for compressed cycles: 18-year gap to 2020 TikTok revival, ongoing as of 2025.',
      origin: 1998,
      ancestors: [],
      curve: [
        { year: 2001, value: 88 },
        { year: 2008, value: 25 },
        { year: 2015, value: 18 },
        { year: 2020, value: 60 },
        { year: 2023, value: 90 },
        { year: 2025, value: 88 },
      ],
      signals: ['tiktok-native', 'nostalgia', 'gen-z'],
      tags: ['nostalgic', 'graphic', 'denim'],
    },
    {
      id: 'low-rise',
      label: 'Low-Rise Denim',
      tagline: 'Hip-skimming waistbands, visible belt',
      description:
        'Y2K substyle: 2001-05 peak, declared dead 2007, returned 2022 with TikTok-Gen-Z. Trades places with high-waist as the dominant denim silhouette every ~15-20 years.',
      origin: 2000,
      parentId: 'y2k',
      ancestors: ['y2k', 'bell-bottoms'],
      curve: [
        { year: 2003, value: 90 },
        { year: 2008, value: 35 },
        { year: 2015, value: 12 },
        { year: 2022, value: 65 },
        { year: 2025, value: 80 },
      ],
      signals: ['tiktok-native', 'silhouette', 'denim'],
      tags: ['silhouette', 'denim', 'nostalgic'],
    },
    {
      id: 'indie-sleaze',
      label: 'Indie Sleaze',
      tagline: 'Flash photography, American Apparel, neon, party',
      description:
        '2006-12 NYC/Cobrasnake era — overexposed flash, Cory Kennedy, MGMT. Declared a comeback in 2022 by trend forecasters; partial revival, weaker than Y2K.',
      origin: 2006,
      ancestors: [],
      curve: [
        { year: 2008, value: 70 },
        { year: 2013, value: 28 },
        { year: 2018, value: 12 },
        { year: 2022, value: 48 },
        { year: 2025, value: 55 },
      ],
      signals: ['nightlife', 'tiktok-native', 'pinterest era'],
      tags: ['subculture', 'nostalgic'],
    },
    {
      id: 'athleisure',
      label: 'Athleisure',
      tagline: 'Leggings, hoodies, performance fabrics worn out of context',
      description:
        'Lululemon/Athleta wave 2010-16. Quietly absorbed into mainstream wardrobe; no longer a "trend" but a baseline. Gorpcore is the current outdoor-leaning descendant.',
      origin: 2009,
      ancestors: [],
      curve: [
        { year: 2014, value: 78 },
        { year: 2018, value: 70 },
        { year: 2022, value: 58 },
        { year: 2025, value: 52 },
      ],
      signals: ['performance', 'comfort', 'mainstream'],
      tags: ['casual', 'performance'],
    },
    {
      id: 'gorpcore',
      label: 'Gorpcore',
      tagline: 'Technical outerwear, hiking shoes, urban outdoor',
      description:
        'Salomon, Arc\'teryx, Patagonia worn in cities. Emerged 2017, mainstream by 2021 (Hoka craze, Salomon XT-6). Currently saturating; quiet luxury threatens replacement.',
      origin: 2017,
      parentId: 'athleisure',
      ancestors: ['athleisure'],
      curve: [
        { year: 2019, value: 45 },
        { year: 2022, value: 75 },
        { year: 2024, value: 82 },
        { year: 2025, value: 78 },
      ],
      signals: ['technical', 'streetwear', 'tiktok-native'],
      tags: ['casual', 'performance', 'modern'],
    },
    {
      id: 'balletcore',
      label: 'Balletcore',
      tagline: 'Pointe-shoe pinks, leotards, leg warmers, tulle',
      description:
        'Late 2022 microtrend out of "soft girl" / Sofia Coppola visual cluster. Compressed peak — saturated within 18 months. Lives on inside coquette.',
      origin: 2022,
      ancestors: [],
      curve: [
        { year: 2022, value: 35 },
        { year: 2023, value: 78 },
        { year: 2024, value: 60 },
        { year: 2025, value: 45 },
      ],
      signals: ['tiktok-native', 'soft girl', 'fast cycle'],
      tags: ['feminine', 'soft', 'modern'],
    },
    {
      id: 'coquette',
      label: 'Coquette',
      tagline: 'Bows, ribbons, lace, Lolita-adjacent',
      description:
        'Tumblr-rooted feminine maximalism (~2014-15) reborn on TikTok 2022+. Bow-on-everything aesthetic. Overlap with balletcore but more decorative.',
      origin: 2014,
      ancestors: ['balletcore'],
      curve: [
        { year: 2016, value: 35 },
        { year: 2020, value: 22 },
        { year: 2023, value: 75 },
        { year: 2024, value: 80 },
        { year: 2025, value: 70 },
      ],
      signals: ['tiktok-native', 'soft girl', 'maximal feminine'],
      tags: ['feminine', 'maximal', 'modern'],
    },
    {
      id: 'quiet-luxury',
      label: 'Quiet Luxury / Old Money',
      tagline: 'Logo-free, neutral palette, knit polos, Loro Piana',
      description:
        'Backlash to logo-mania and gorpcore loudness. Succession-fueled (Tom Wambsgans, Kendall Roy). The Row, Brunello Cucinelli. Strong correlate of late-cycle economic uncertainty — same DNA as 1990s minimalism.',
      origin: 2022,
      parentId: 'preppy',
      ancestors: ['preppy'],
      curve: [
        { year: 2022, value: 35 },
        { year: 2023, value: 70 },
        { year: 2024, value: 88 },
        { year: 2025, value: 82 },
      ],
      signals: ['anti-logo', 'aspirational', 'tiktok-native'],
      tags: ['classic', 'modern', 'luxury'],
    },
    {
      id: 'minimalism-90s',
      label: '90s Minimalism',
      tagline: 'Slip dresses, square necks, restraint, Helmut Lang',
      description:
        'Calvin Klein / Helmut Lang / Jil Sander 1993-99. The aesthetic ancestor of quiet luxury. Microtrend revivals 2014, 2024.',
      origin: 1993,
      ancestors: [],
      curve: [
        { year: 1996, value: 75 },
        { year: 2002, value: 28 },
        { year: 2014, value: 55 },
        { year: 2018, value: 35 },
        { year: 2024, value: 60 },
        { year: 2025, value: 65 },
      ],
      signals: ['restraint', 'craft', 'anti-logo'],
      tags: ['classic', 'minimal'],
      pioneers: ['Helmut Lang', 'Jil Sander', 'Calvin Klein'],
    },
  ],
  cycleNotes: [
    'Bell bottoms (1972 peak) returned ~1998, then again ~2022 — almost exactly the canonical 22-year cycle, twice in a row.',
    'Y2K compresses the cycle: 18-year gap from 2003 peak to 2021 mainstream return (TikTok era), and the revival is now larger than the original.',
    'Quiet luxury 2023+ is the textbook backlash trend: a counter-reaction to gorpcore loudness and logo-mania, mapping the same DNA as 1990s minimalism.',
    'Balletcore is a clean accelerated-cycle case: trough → peak → fade in under 24 months, vs the canonical 22.',
    'Preppy / old money has now had three distinct waves (1985, 2008, 2023) — closer to a 15-year cycle than a 22-year one in this category.',
  ],
  yearRange: { start: 1955, end: 2030 },
}

export const WALKIN_DATASET: IndustryDataset = {
  industry: {
    id: 'walkin',
    label: 'Walk-in / Flash',
    blurb: 'Motif-level cycles tied to films, celebrities, and viral moments. Cycle window 4-8 years.',
    status: 'active',
  },
  styles: [
    {
      id: 'butterfly',
      label: 'Butterfly',
      tagline: 'Y2K signifier; perennial women\'s motif',
      description:
        'Surged with Britney/Aaliyah Y2K era (2000-03), faded mid-2000s, returned hard 2020+ on TikTok. The flagship event-driven motif: small fineline butterflies are now a dominant first-tattoo choice for women under 30.',
      origin: 1995,
      ancestors: [],
      curve: [
        { year: 2001, value: 78 },
        { year: 2008, value: 30 },
        { year: 2018, value: 22 },
        { year: 2022, value: 78 },
        { year: 2025, value: 82 },
      ],
      signals: ['y2k revival', 'tiktok-native', 'feminine micro'],
      tags: ['feminine', 'micro', 'fineline-friendly'],
      triggers: [
        { year: 2001, name: 'Britney Spears Crazy / Toxic era', medium: 'celebrity', impact: 'high' },
        { year: 2003, name: 'Mariah Carey butterfly motif', medium: 'celebrity', impact: 'medium' },
        { year: 2020, name: 'Y2K TikTok revival', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'dolphin',
      label: 'Dolphin',
      tagline: 'Lower-back wave, 2000-2005 women\'s spike',
      description:
        'Defining motif of the early-2000s "tramp stamp" era. Tied to spring-break Sea World aesthetics and pre-Y2K beach culture. Sharp decline post-2008; hasn\'t returned and probably won\'t in this form.',
      origin: 1998,
      ancestors: [],
      curve: [
        { year: 2002, value: 75 },
        { year: 2007, value: 45 },
        { year: 2012, value: 18 },
        { year: 2020, value: 8 },
        { year: 2025, value: 6 },
      ],
      signals: ['pinterest era', 'beach culture', 'fast cycle'],
      tags: ['feminine', 'declined', 'lower-back'],
      triggers: [
        { year: 1996, name: 'Free Willy 3', medium: 'film', impact: 'low' },
        { year: 2000, name: 'Spring break / MTV beach culture', medium: 'tv', impact: 'high' },
      ],
    },
    {
      id: 'fairy',
      label: 'Fairy',
      tagline: 'Mid-2000s women\'s flash, hip/back placement',
      description:
        'Tinkerbell-influenced fairies on hips and shoulder blades, 2004-2009 peak. Faded; partial micro-revival inside 2024 fairycore aesthetic but not as the dominant motif it once was.',
      origin: 2002,
      ancestors: [],
      curve: [
        { year: 2006, value: 70 },
        { year: 2012, value: 25 },
        { year: 2020, value: 12 },
        { year: 2024, value: 26 },
        { year: 2025, value: 30 },
      ],
      signals: ['fantasy', 'feminine', 'fairycore-adjacent'],
      tags: ['feminine', 'illustrative'],
      triggers: [
        { year: 2003, name: 'Peter Pan (live action)', medium: 'film', impact: 'medium' },
        { year: 2008, name: 'Tinker Bell (Disney)', medium: 'film', impact: 'medium' },
      ],
    },
    {
      id: 'star-cluster',
      label: 'Stars / Star Cluster',
      tagline: 'Wrist and neckline trails, 2005-2012',
      description:
        'Small five-point stars in clusters, often trailing from a larger one. Hugely common 2005-2012 then aged out. Constellation tattoos (separate id) absorbed the demand from 2018+.',
      origin: 2003,
      ancestors: [],
      curve: [
        { year: 2007, value: 72 },
        { year: 2014, value: 30 },
        { year: 2020, value: 15 },
        { year: 2025, value: 12 },
      ],
      signals: ['scenester', 'mall tattoo', 'declined'],
      tags: ['feminine', 'graphic', 'declined'],
      triggers: [
        { year: 2005, name: 'Rihanna shoulder stars', medium: 'celebrity', impact: 'medium' },
      ],
    },
    {
      id: 'infinity-symbol',
      label: 'Infinity Symbol',
      tagline: '"Live laugh love" of tattoos',
      description:
        '∞ alone or merged with words, a heart, or feathers. 2010-2015 peak driven by Pinterest-quote culture. Heavy decline since; now considered a mall-tattoo cliché but still walked-in.',
      origin: 2009,
      ancestors: [],
      curve: [
        { year: 2012, value: 78 },
        { year: 2017, value: 45 },
        { year: 2022, value: 22 },
        { year: 2025, value: 18 },
      ],
      signals: ['pinterest era', 'declined', 'walk-in standard'],
      tags: ['feminine', 'graphic', 'declined'],
      triggers: [
        { year: 2010, name: 'Pinterest visual era', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'feather-to-birds',
      label: 'Feather Dissolving Into Birds',
      tagline: 'Single feather where tip becomes flying birds',
      description:
        'A graphic device popularized 2011-2015, often paired with a quote. Tied to Pinterest/Tumblr era and migration/freedom symbolism. Saturated then declined.',
      origin: 2010,
      ancestors: [],
      curve: [
        { year: 2013, value: 70 },
        { year: 2018, value: 30 },
        { year: 2025, value: 14 },
      ],
      signals: ['pinterest era', 'symbolic', 'declined'],
      tags: ['graphic', 'declined'],
      triggers: [
        { year: 2011, name: 'Tumblr image culture', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'anchor',
      label: 'Anchor',
      tagline: 'Hipster nautical wave, 2012-2017',
      description:
        'Sailor Jerry classic that broke into mainstream walk-in via the 2012-2016 hipster nautical aesthetic (anchors + roses + swallows). Still common but no longer trending.',
      origin: 2010,
      parentId: 'compass-rose',
      ancestors: [],
      curve: [
        { year: 2014, value: 72 },
        { year: 2018, value: 50 },
        { year: 2025, value: 32 },
      ],
      signals: ['nautical', 'hipster wave'],
      tags: ['unisex', 'classic'],
      triggers: [
        { year: 2003, name: 'Pirates of the Caribbean', medium: 'film', impact: 'medium' },
      ],
    },
    {
      id: 'compass-rose',
      label: 'Compass Rose',
      tagline: 'Nautical compass, often with mountains or coordinates',
      description:
        'Travel-symbolism wave 2014-2019, frequently combined with mountains, oceans, or coordinates of meaningful places. Heavy in walk-in flash for "wanderlust" demographic.',
      origin: 2013,
      ancestors: [],
      curve: [
        { year: 2016, value: 78 },
        { year: 2020, value: 55 },
        { year: 2025, value: 38 },
      ],
      signals: ['wanderlust', 'instagram-native'],
      tags: ['unisex', 'graphic'],
    },
    {
      id: 'arrow',
      label: 'Arrow',
      tagline: 'Forearm arrows, often in a row',
      description:
        '2014-2017 microtrend. Single arrow on forearm/finger, sometimes in pairs as friendship or sibling tattoos. Faded fast.',
      origin: 2013,
      ancestors: [],
      curve: [
        { year: 2015, value: 68 },
        { year: 2019, value: 30 },
        { year: 2025, value: 14 },
      ],
      signals: ['minimalism', 'friendship', 'fast cycle'],
      tags: ['unisex', 'declined', 'micro'],
    },
    {
      id: 'mountain-range',
      label: 'Minimalist Mountain Range',
      tagline: 'Single-line peaks, often on forearm or rib',
      description:
        '2015-2020 peak. Outdoorsy / wanderlust signifier, often combined with sun, moon, or compass. Still walked-in but past peak — gorpcore fashion absorbed the same demographic.',
      origin: 2014,
      ancestors: [],
      curve: [
        { year: 2017, value: 72 },
        { year: 2021, value: 60 },
        { year: 2025, value: 42 },
      ],
      signals: ['wanderlust', 'minimalism', 'gorpcore-adjacent'],
      tags: ['unisex', 'minimal'],
    },
    {
      id: 'rose-with-dagger',
      label: 'Rose with Dagger',
      tagline: 'Neo-traditional flash standard',
      description:
        'Classic neo-traditional pairing — rose pierced by a dagger, often with banner. Climbed steadily 2015-now, now a flash-sheet staple. Doesn\'t age out the way trend motifs do.',
      origin: 2010,
      ancestors: [],
      curve: [
        { year: 2014, value: 50 },
        { year: 2020, value: 70 },
        { year: 2025, value: 75 },
      ],
      signals: ['neo-traditional', 'durable', 'flash standard'],
      tags: ['unisex', 'illustrative', 'classic'],
    },
    {
      id: 'snake',
      label: 'Snake',
      tagline: 'Forearm and ribcage snakes, fineline or traditional',
      description:
        'Strong climb 2018-now. Symbolism (transformation, danger) plus high-fashion runway adoption. Both fineline minimal and full traditional palette.',
      origin: 2017,
      ancestors: [],
      curve: [
        { year: 2019, value: 55 },
        { year: 2022, value: 78 },
        { year: 2025, value: 84 },
      ],
      signals: ['symbolic', 'gucci-effect', 'instagram-native'],
      tags: ['unisex', 'illustrative'],
      triggers: [
        { year: 2017, name: 'Gucci snake motifs (Alessandro Michele era)', medium: 'celebrity', impact: 'medium' },
        { year: 2018, name: 'Taylor Swift Reputation era', medium: 'music', impact: 'medium' },
      ],
    },
    {
      id: 'moth',
      label: 'Moth',
      tagline: 'Symmetric moth, often with skull or moon',
      description:
        'Gothic-adjacent moth tattoos — death\'s-head, luna, atlas. Sharp climb post-2020 alongside dark academia and cottagecore. Very TikTok.',
      origin: 2019,
      ancestors: [],
      curve: [
        { year: 2020, value: 30 },
        { year: 2023, value: 70 },
        { year: 2025, value: 78 },
      ],
      signals: ['dark academia', 'tiktok-native', 'symbolic'],
      tags: ['feminine', 'gothic', 'fineline-friendly'],
    },
    {
      id: 'tiny-heart',
      label: 'Tiny Heart',
      tagline: 'Coin-sized red or black heart, anywhere',
      description:
        'Flagship of the fineline-micro era. Often paired with initials or stand-alone. 2019-now, still climbing. Closest thing to an "evergreen" motif of the current decade.',
      origin: 2018,
      ancestors: [],
      curve: [
        { year: 2020, value: 65 },
        { year: 2023, value: 82 },
        { year: 2025, value: 88 },
      ],
      signals: ['fineline-micro', 'gen-z', 'tiktok-native'],
      tags: ['feminine', 'micro', 'fineline-friendly'],
    },
    {
      id: 'lightning-bolt',
      label: 'Lightning Bolt',
      tagline: 'Single fineline bolt, finger or behind ear',
      description:
        '2019-2022 microtrend, often as small finger or ear tattoo. Faded as a microtrend but persists as a flash option.',
      origin: 2018,
      ancestors: [],
      curve: [
        { year: 2020, value: 60 },
        { year: 2022, value: 50 },
        { year: 2025, value: 28 },
      ],
      signals: ['micro', 'finger', 'fast cycle'],
      tags: ['unisex', 'micro'],
    },
    {
      id: 'bat',
      label: 'Bat',
      tagline: 'Gothic resurgence motif, 2022+',
      description:
        'Bats — sometimes tribal, increasingly fineline gothic — surged post-Wednesday TV show. Coquette/dark-feminine overlap. Strong 2023+ climb.',
      origin: 2021,
      ancestors: [],
      curve: [
        { year: 2022, value: 35 },
        { year: 2024, value: 70 },
        { year: 2025, value: 78 },
      ],
      signals: ['dark feminine', 'gothic', 'tiktok-native'],
      tags: ['feminine', 'gothic'],
      triggers: [
        { year: 2022, name: 'Wednesday (Netflix)', medium: 'tv', impact: 'high' },
        { year: 2023, name: 'Coquette / dark feminine TikTok wave', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'mushroom',
      label: 'Mushroom',
      tagline: 'Cottagecore amanita, often with mycelium',
      description:
        'Tied to 2020-21 cottagecore wave. Red-cap amanita most common; some psychedelic / 60s-revival overlap. Stable now but no longer climbing.',
      origin: 2019,
      ancestors: [],
      curve: [
        { year: 2021, value: 65 },
        { year: 2023, value: 60 },
        { year: 2025, value: 50 },
      ],
      signals: ['cottagecore', 'psychedelic revival', 'pinterest era'],
      tags: ['feminine', 'illustrative'],
    },
    {
      id: 'evil-eye',
      label: 'Evil Eye',
      tagline: 'Nazar / hamsa eye, often combined with hamsa',
      description:
        'Spiritual-protection motif, climbing 2018-now. Driven by celebrity adoption (Gigi Hadid, Hailey Bieber) and broader Mediterranean/Middle Eastern aesthetic mainstreaming.',
      origin: 2017,
      ancestors: [],
      curve: [
        { year: 2019, value: 55 },
        { year: 2022, value: 72 },
        { year: 2025, value: 78 },
      ],
      signals: ['spiritual', 'celebrity', 'instagram-native'],
      tags: ['unisex', 'symbolic'],
      triggers: [
        { year: 2018, name: 'Gigi Hadid evil eye', medium: 'celebrity', impact: 'medium' },
      ],
    },
    {
      id: 'constellation',
      label: 'Constellation',
      tagline: 'Star-map birth-sign or matching friend tattoo',
      description:
        'Replaced star-clusters as the small-stars motif. Often birth constellation or matching friend / sibling tattoos. Steady plateau.',
      origin: 2017,
      ancestors: [],
      curve: [
        { year: 2019, value: 60 },
        { year: 2022, value: 70 },
        { year: 2025, value: 65 },
      ],
      signals: ['astrology', 'friendship', 'fineline-micro'],
      tags: ['feminine', 'micro'],
    },
    {
      id: 'cherry',
      label: 'Cherry',
      tagline: 'Coquette pair-of-cherries, hand or shoulder',
      description:
        'Coquette/balletcore-adjacent. Pair of cherries with stem, often red ink only. 2022+ climb tied to coquette TikTok aesthetic.',
      origin: 2021,
      ancestors: [],
      curve: [
        { year: 2022, value: 35 },
        { year: 2024, value: 65 },
        { year: 2025, value: 70 },
      ],
      signals: ['coquette', 'tiktok-native', 'soft girl'],
      tags: ['feminine', 'micro'],
      triggers: [
        { year: 2022, name: 'Coquette TikTok wave', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'cherub',
      label: 'Cherub',
      tagline: 'Renaissance putto, fineline or full color',
      description:
        'Y2K-revival aesthetic — Botticelli/Raphael cherubs. Often paired with hearts or hands. Climbed 2021+ alongside Y2K and old-money waves.',
      origin: 2020,
      ancestors: [],
      curve: [
        { year: 2022, value: 45 },
        { year: 2024, value: 68 },
        { year: 2025, value: 70 },
      ],
      signals: ['y2k revival', 'classical', 'tiktok-native'],
      tags: ['feminine', 'illustrative'],
    },
    {
      id: 'stitch-cartoon',
      label: 'Stitch / Cartoon Imports',
      tagline: 'Lilo & Stitch (and similar) cartoon characters',
      description:
        'Modest baseline since the original 2002 film. Big spike with the 2024 live-action remake — Stitch became the dominant kids/young-adult walk-in cartoon motif. Pikachu, Hello Kitty, and other iconic characters cycle alongside.',
      origin: 2002,
      ancestors: [],
      curve: [
        { year: 2003, value: 35 },
        { year: 2010, value: 25 },
        { year: 2018, value: 30 },
        { year: 2024, value: 70 },
        { year: 2025, value: 76 },
      ],
      signals: ['nostalgia', 'film tie-in', 'tiktok-native'],
      tags: ['unisex', 'illustrative', 'character'],
      triggers: [
        { year: 2002, name: 'Lilo & Stitch (original)', medium: 'film', impact: 'medium' },
        { year: 2024, name: 'Lilo & Stitch (live action)', medium: 'film', impact: 'high' },
      ],
    },
    {
      id: 'sugar-skull',
      label: 'Sugar Skull / Day of the Dead',
      tagline: 'Decorated calavera, often with roses',
      description:
        'Coco (2017) drove a noticeable mid-2010s spike. Pre-existing in Chicano culture; mainstream walk-in adoption faded but never zeroed.',
      origin: 2010,
      ancestors: [],
      curve: [
        { year: 2014, value: 55 },
        { year: 2018, value: 65 },
        { year: 2022, value: 50 },
        { year: 2025, value: 42 },
      ],
      signals: ['cultural', 'film tie-in'],
      tags: ['unisex', 'illustrative', 'colored'],
      triggers: [
        { year: 2017, name: 'Coco (Pixar)', medium: 'film', impact: 'medium' },
      ],
    },
    {
      id: 'demogorgon-stranger',
      label: 'Stranger Things motifs',
      tagline: 'Demogorgon, Eleven, "Friends Don\'t Lie"',
      description:
        'Show-driven walk-in spikes during each Stranger Things season (2016, 2019, 2022). Mostly Demogorgon and quote tattoos. Drops between seasons.',
      origin: 2016,
      ancestors: [],
      curve: [
        { year: 2017, value: 35 },
        { year: 2019, value: 50 },
        { year: 2022, value: 55 },
        { year: 2025, value: 30 },
      ],
      signals: ['fandom', 'fast cycle', 'tv tie-in'],
      tags: ['unisex', 'illustrative', 'character'],
      triggers: [
        { year: 2016, name: 'Stranger Things S1 (Netflix)', medium: 'tv', impact: 'medium' },
        { year: 2022, name: 'Stranger Things S4', medium: 'tv', impact: 'high' },
      ],
    },
    {
      id: 'rihanna-finger-script',
      label: 'Single-letter Finger / Wrist Script',
      tagline: 'Initial or short word, pinky or wrist',
      description:
        'Took off 2017-2020. Driven by celebrity finger tattoos (Rihanna, Hailey Bieber\'s "G", Ariana Grande). Saturated then plateaued.',
      origin: 2014,
      ancestors: [],
      curve: [
        { year: 2017, value: 65 },
        { year: 2020, value: 72 },
        { year: 2024, value: 55 },
        { year: 2025, value: 50 },
      ],
      signals: ['celebrity', 'micro', 'finger'],
      tags: ['unisex', 'micro', 'lettering'],
      triggers: [
        { year: 2018, name: 'Hailey Bieber "G" finger tattoo', medium: 'celebrity', impact: 'medium' },
      ],
    },
  ],
  cycleNotes: [
    'Walk-in motifs cycle in 4-8 years, not 22. Dolphins (2002 peak) never came back; butterflies did because Y2K returned wholesale via TikTok.',
    'Triggers explain the gaps: Lilo & Stitch (2002) was a modest baseline event, but the 2024 live-action remake produced a much larger walk-in spike. Moana (2016) did not produce a comparable wave despite similar studio support — note this when forecasting future film triggers.',
    'A motif aging out of "trending" doesn\'t mean it stops walking in. Infinity symbols, anchors, and small stars are still daily walk-ins despite being out of fashion — flash sheets reflect this.',
    'Celebrity-anchored motifs (single-letter finger script, evil eye, stars) follow the celebrity\'s relevance more than a cultural cycle. When the celebrity moment fades, so does the motif.',
    'Gothic/dark-feminine motifs (bats, moths, snakes) are currently the strongest rising cluster among women under 30, displacing the 2010s bohemian cluster (feathers, arrows, mountains).',
  ],
  yearRange: { start: 1995, end: 2030 },
}

export const HAWAII_DATASET: IndustryDataset = {
  industry: {
    id: 'hawaii-souvenir',
    label: 'Hawaii Souvenir',
    blurb: 'Tourist + local Hawaiian motifs. Many run evergreen because they signify the trip, not the trend.',
    status: 'active',
  },
  styles: [
    {
      id: 'honu-turtle',
      label: 'Honu (Sea Turtle)',
      tagline: 'Hawaiian green sea turtle, often with tribal-pattern shell',
      description:
        'The most enduring Hawaiian souvenir motif. Carries cultural weight (longevity, navigation, aumakua for some families) plus tourist appeal. Tribal-shell variants peaked alongside the 1990s tribal wave but the motif itself never declined.',
      origin: 1985,
      ancestors: [],
      curve: [
        { year: 1995, value: 55 },
        { year: 2003, value: 70 },
        { year: 2012, value: 72 },
        { year: 2020, value: 78 },
        { year: 2025, value: 80 },
      ],
      signals: ['cultural', 'protective', 'evergreen', 'tribal-shell'],
      tags: ['cultural', 'evergreen', 'unisex'],
    },
    {
      id: 'plumeria',
      label: 'Plumeria',
      tagline: 'Five-petal Hawaiian flower, often a single bloom',
      description:
        'The signature Hawaii flower for tourist tattoos. Perennial demand; spiked sharply 2014-2018 alongside the mainland Pinterest/fineline wave that elevated minimalist florals.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 2000, value: 55 },
        { year: 2010, value: 60 },
        { year: 2016, value: 82 },
        { year: 2022, value: 75 },
        { year: 2025, value: 78 },
      ],
      signals: ['floral', 'pinterest era', 'fineline-friendly', 'evergreen'],
      tags: ['feminine', 'floral', 'evergreen'],
    },
    {
      id: 'hibiscus',
      label: 'Hibiscus',
      tagline: 'Yellow ʻōhiʻa lehua-style or red hibiscus, state flower',
      description:
        'Hawaiʻi state flower (yellow hibiscus / maʻo hau hele). Reliable tourist standard. Tracks plumeria but slightly less spiked by the fineline wave because the bloom is more graphic.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 2000, value: 60 },
        { year: 2010, value: 62 },
        { year: 2018, value: 70 },
        { year: 2025, value: 72 },
      ],
      signals: ['floral', 'state symbol', 'evergreen'],
      tags: ['feminine', 'floral', 'evergreen', 'colored'],
    },
    {
      id: 'manta-ray',
      label: 'Manta Ray',
      tagline: 'Single ray silhouette, often facing forward',
      description:
        'Climbed steadily as Big Island night manta dives became an iconic visitor experience (Kona, 2008+). Now one of the strongest "I had a real Hawaii moment" souvenir motifs.',
      origin: 2005,
      ancestors: [],
      curve: [
        { year: 2008, value: 35 },
        { year: 2014, value: 60 },
        { year: 2020, value: 75 },
        { year: 2025, value: 80 },
      ],
      signals: ['experience-anchored', 'dive culture', 'instagram-native'],
      tags: ['unisex', 'aquatic'],
    },
    {
      id: 'hammerhead-shark',
      label: 'Hammerhead Shark',
      tagline: 'Polynesian aumakua / family protector',
      description:
        'Carries serious cultural weight in Native Hawaiian tradition (aumakua / family guardian). Climbed alongside Polynesian heritage revival; commonly requested by locals and visitors with family ties.',
      origin: 1995,
      ancestors: [],
      curve: [
        { year: 2000, value: 40 },
        { year: 2012, value: 60 },
        { year: 2020, value: 75 },
        { year: 2025, value: 78 },
      ],
      signals: ['cultural', 'aumakua', 'protective'],
      tags: ['unisex', 'cultural', 'aquatic'],
    },
    {
      id: 'tropical-dolphin',
      label: 'Dolphin (Hawaii context)',
      tagline: 'Lower-back / shoulder dolphins, 2000s tourist standard',
      description:
        'The same early-2000s dolphin wave that hit the mainland came through Hawaii souvenir flash sheets just as hard. Sharp decline post-2008; nearly dormant now even in tourist context.',
      origin: 1998,
      ancestors: [],
      curve: [
        { year: 2002, value: 80 },
        { year: 2008, value: 50 },
        { year: 2015, value: 20 },
        { year: 2025, value: 12 },
      ],
      signals: ['fast cycle', 'beach culture', 'declined'],
      tags: ['feminine', 'declined', 'aquatic'],
    },
    {
      id: 'tiki-head',
      label: 'Tiki God Head',
      tagline: 'Carved-wood ki\'i face, often square-jawed',
      description:
        'Classic Hawaiian flash. Faded slightly with broader cultural-appropriation awareness but remains a strong walk-in choice, especially in single-color blackwork.',
      origin: 1985,
      ancestors: [],
      curve: [
        { year: 1995, value: 60 },
        { year: 2008, value: 55 },
        { year: 2018, value: 45 },
        { year: 2025, value: 42 },
      ],
      signals: ['carving heritage', 'classic flash'],
      tags: ['unisex', 'cultural', 'classic'],
    },
    {
      id: 'gecko',
      label: 'Gecko',
      tagline: 'Hawaiian gecko silhouette, often tribal-pattern body',
      description:
        'Iconic enough to appear on every souvenir T-shirt and sticker — translates directly into walk-in tattoo flash. Modest steady demand; doesn\'t cycle hard.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 2000, value: 50 },
        { year: 2012, value: 48 },
        { year: 2025, value: 45 },
      ],
      signals: ['souvenir crossover', 'tribal-pattern body'],
      tags: ['unisex', 'evergreen'],
    },
    {
      id: 'wave-pipeline',
      label: 'Wave / Pipeline',
      tagline: 'Curling wave silhouette, often single-line',
      description:
        'North Shore visibility (Pipeline season every December) keeps this perennial. Single-line minimalist version surged with the 2017+ fineline wave.',
      origin: 1995,
      ancestors: [],
      curve: [
        { year: 2005, value: 55 },
        { year: 2015, value: 65 },
        { year: 2020, value: 75 },
        { year: 2025, value: 78 },
      ],
      signals: ['surf culture', 'fineline-friendly', 'evergreen'],
      tags: ['unisex', 'minimal', 'evergreen'],
    },
    {
      id: 'surfboard',
      label: 'Surfboard',
      tagline: 'Longboard or shortboard silhouette',
      description:
        'Classic Hawaii souvenir flash; slow steady demand. Sometimes paired with a wave or palm tree.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 2000, value: 50 },
        { year: 2015, value: 50 },
        { year: 2025, value: 48 },
      ],
      signals: ['surf culture', 'classic flash'],
      tags: ['unisex', 'classic'],
    },
    {
      id: 'palm-tree-silhouette',
      label: 'Palm Tree Silhouette',
      tagline: 'Single coconut palm, often with sun behind',
      description:
        'Simple, durable tourist motif. Strong climb with the 2017+ single-needle micro wave (single-line palm).',
      origin: 1995,
      ancestors: [],
      curve: [
        { year: 2005, value: 50 },
        { year: 2015, value: 60 },
        { year: 2022, value: 75 },
        { year: 2025, value: 78 },
      ],
      signals: ['fineline-micro', 'tropical', 'evergreen'],
      tags: ['unisex', 'minimal', 'evergreen'],
    },
    {
      id: 'rising-sun',
      label: 'Rising Sun / Sunset',
      tagline: 'Stylized sun with rays, often over horizon',
      description:
        'Steady demand. Hawaii sunrise/sunset imagery is heavily marketed (Haleakalā summit, Mauna Kea) so it crosses over from tourist photos into tattoos.',
      origin: 1995,
      ancestors: [],
      curve: [
        { year: 2005, value: 50 },
        { year: 2018, value: 60 },
        { year: 2025, value: 65 },
      ],
      signals: ['landscape', 'tourist photo', 'evergreen'],
      tags: ['unisex', 'graphic', 'evergreen'],
    },
    {
      id: 'pineapple-hawaii',
      label: 'Pineapple',
      tagline: 'Pineapple with crown, often with sunglasses',
      description:
        'Sharp 2014-2018 spike driven by mainland Pinterest/Instagram pineapple-as-icon wave. Hawaii context amplified it (Dole plantation, Maui Gold). Cooling now but still walks in.',
      origin: 2010,
      ancestors: [],
      curve: [
        { year: 2014, value: 55 },
        { year: 2017, value: 80 },
        { year: 2022, value: 50 },
        { year: 2025, value: 38 },
      ],
      signals: ['pinterest era', 'instagram-native', 'fast cycle'],
      tags: ['feminine', 'graphic', 'tropical'],
      triggers: [
        { year: 2014, name: 'Pinterest pineapple-as-icon visual wave', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'ohana-script',
      label: '"ʻOhana" Script',
      tagline: 'Hawaiian word for family, often in cursive',
      description:
        'Took off after Lilo & Stitch (2002) made the line "ʻOhana means family" famous outside Hawaii. Sustained walk-in demand, with another bump after the 2024 live-action remake.',
      origin: 2003,
      ancestors: [],
      curve: [
        { year: 2005, value: 55 },
        { year: 2012, value: 65 },
        { year: 2020, value: 70 },
        { year: 2024, value: 78 },
        { year: 2025, value: 80 },
      ],
      signals: ['film tie-in', 'family memorial', 'lettering'],
      tags: ['unisex', 'lettering', 'evergreen'],
      triggers: [
        { year: 2002, name: 'Lilo & Stitch (original)', medium: 'film', impact: 'high' },
        { year: 2024, name: 'Lilo & Stitch (live action)', medium: 'film', impact: 'high' },
      ],
    },
    {
      id: 'aloha-script',
      label: '"Aloha" Script',
      tagline: '"Aloha" or "Mahalo" lettering, often with a flower',
      description:
        'Perennial souvenir lettering. Tracks a slower curve than ʻOhana since it lacks a single film driver — more a steady tourist standard.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 2000, value: 55 },
        { year: 2015, value: 55 },
        { year: 2025, value: 55 },
      ],
      signals: ['lettering', 'tourist standard'],
      tags: ['unisex', 'lettering', 'evergreen'],
    },
    {
      id: 'polynesian-armband',
      label: 'Polynesian Armband',
      tagline: 'Marquesan / Samoan-style geometric band',
      description:
        'Late-1990s flash-shop standard ("tribal armband"). Generic versions declined hard with cultural-appropriation awareness; authentic tatau by Polynesian artists with proper protocol is the rising path.',
      origin: 1985,
      ancestors: [],
      curve: [
        { year: 1998, value: 88 },
        { year: 2008, value: 55 },
        { year: 2018, value: 30 },
        { year: 2025, value: 35 },
      ],
      signals: ['cultural', 'cultural-respect-shift', 'declined-then-stabilizing'],
      tags: ['unisex', 'cultural', 'blackwork'],
    },
    {
      id: 'flower-lei',
      label: 'Flower Lei',
      tagline: 'Circular or wrapping flower lei',
      description:
        'Perennial. Often as an ankle wrap or shoulder garland. Climbs slightly with broader floral/fineline waves.',
      origin: 1995,
      ancestors: [],
      curve: [
        { year: 2005, value: 50 },
        { year: 2018, value: 60 },
        { year: 2025, value: 65 },
      ],
      signals: ['floral', 'celebration', 'evergreen'],
      tags: ['feminine', 'floral', 'evergreen'],
    },
    {
      id: 'mauna-kea-silhouette',
      label: 'Mauna Kea / Maunakea Silhouette',
      tagline: 'Sacred mountain silhouette, sometimes with "Kapu Aloha"',
      description:
        'Niche before 2019. Surged sharply during the Mauna Kea / Kūkiaʻimauna protests (2019-20) as locals took protection-symbol tattoos. Ongoing demand among locals; less common from visitors.',
      origin: 2010,
      ancestors: [],
      curve: [
        { year: 2015, value: 18 },
        { year: 2019, value: 55 },
        { year: 2022, value: 60 },
        { year: 2025, value: 55 },
      ],
      signals: ['protest', 'local solidarity', 'sacred'],
      tags: ['unisex', 'cultural', 'symbolic'],
      triggers: [
        { year: 2019, name: 'Kūkiaʻimauna / Mauna Kea TMT protests', medium: 'viral', impact: 'high' },
      ],
    },
    {
      id: 'petroglyph',
      label: 'Petroglyph (kiʻi pōhaku)',
      tagline: 'Stick-figure rock carvings — paddler, family, voyager',
      description:
        'Real Hawaiian rock art (kiʻi pōhaku). Quiet but durable demand. Often used in family memorial work.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 2005, value: 35 },
        { year: 2017, value: 45 },
        { year: 2025, value: 50 },
      ],
      signals: ['cultural', 'memorial', 'heritage'],
      tags: ['unisex', 'cultural', 'minimal'],
    },
    {
      id: 'birds-of-paradise',
      label: 'Bird of Paradise',
      tagline: 'Tropical orange-and-blue strelitzia bloom',
      description:
        'Iconic tropical flower; slow climber with the wider exotic-floral wave 2018+.',
      origin: 2000,
      ancestors: [],
      curve: [
        { year: 2010, value: 35 },
        { year: 2020, value: 55 },
        { year: 2025, value: 60 },
      ],
      signals: ['floral', 'tropical', 'colored'],
      tags: ['feminine', 'floral', 'colored'],
    },
    {
      id: 'sea-horse',
      label: 'Sea Horse',
      tagline: 'Curled tail with bumpy ridges',
      description:
        'Early-2000s tourist favorite alongside dolphins. Faded similarly; partial uptick in fineline-micro versions among 2024 visitors.',
      origin: 1998,
      ancestors: [],
      curve: [
        { year: 2003, value: 60 },
        { year: 2010, value: 38 },
        { year: 2020, value: 18 },
        { year: 2024, value: 28 },
        { year: 2025, value: 30 },
      ],
      signals: ['fast cycle', 'fineline revival'],
      tags: ['feminine', 'aquatic'],
    },
    {
      id: 'island-chain-map',
      label: 'Hawaiian Island Chain',
      tagline: 'Silhouette of all 8 main islands',
      description:
        'Climbed with the wider 2015+ wanderlust / coordinates wave. Often paired with coordinates of a specific island or place.',
      origin: 2013,
      ancestors: [],
      curve: [
        { year: 2015, value: 35 },
        { year: 2020, value: 55 },
        { year: 2025, value: 60 },
      ],
      signals: ['wanderlust', 'instagram-native', 'minimalism'],
      tags: ['unisex', 'minimal', 'graphic'],
    },
    {
      id: 'mokulua-silhouette',
      label: 'Mokulua (Twin Islands)',
      tagline: 'Lanikai twin-island silhouette',
      description:
        'Niche silhouette for Lanikai / Kailua side visitors. Rose with Instagram-driven destination-tattoo trend 2018+.',
      origin: 2015,
      ancestors: [],
      curve: [
        { year: 2018, value: 30 },
        { year: 2022, value: 50 },
        { year: 2025, value: 55 },
      ],
      signals: ['destination-anchored', 'instagram-native'],
      tags: ['unisex', 'minimal'],
    },
    {
      id: 'diamond-head',
      label: 'Diamond Head Silhouette',
      tagline: 'Lēʻahi crater profile',
      description:
        'O\'ahu\'s most photographed landmark, translates to flash. Steady moderate demand from Waikīkī-area visitors.',
      origin: 2000,
      ancestors: [],
      curve: [
        { year: 2010, value: 45 },
        { year: 2020, value: 55 },
        { year: 2025, value: 58 },
      ],
      signals: ['landmark', 'tourist photo'],
      tags: ['unisex', 'minimal'],
    },
    {
      id: 'stitch-hawaii',
      label: 'Stitch (Lilo & Stitch)',
      tagline: 'Disney character with Hawaiian setting; big spike 2024',
      description:
        'Disney\'s Stitch is uniquely embraced in Hawaii because the original 2002 film is set in Kauaʻi. The 2024 live-action remake produced the largest character-driven walk-in spike Hawaii flash has seen in two decades.',
      origin: 2002,
      ancestors: [],
      curve: [
        { year: 2003, value: 40 },
        { year: 2010, value: 30 },
        { year: 2020, value: 35 },
        { year: 2024, value: 78 },
        { year: 2025, value: 82 },
      ],
      signals: ['film tie-in', 'character', 'tiktok-native', 'local-heritage'],
      tags: ['unisex', 'illustrative', 'character'],
      triggers: [
        { year: 2002, name: 'Lilo & Stitch (original)', medium: 'film', impact: 'medium' },
        { year: 2024, name: 'Lilo & Stitch (live action)', medium: 'film', impact: 'high' },
      ],
    },
  ],
  cycleNotes: [
    'Hawaii souvenir tattoos run on a different cycle from mainland flash — many motifs are evergreen because they signify the trip rather than a fashion moment. Hibiscus, honu, plumeria, and gecko don\'t spike or trough the way trendy motifs do.',
    'Cross-over motifs (plumeria via Pinterest 2014, pineapple 2014-2018) DO follow mainland cycles when they hit. Pineapple is the cleanest case: huge spike when the icon went viral, then fade.',
    'Lilo & Stitch (2024) produced the largest character-driven spike Hawaii flash has seen in two decades — big both for tourists and locals because Stitch is local-heritage in a way Moana isn\'t.',
    'Cultural-respect awareness is rebalancing the field — generic flash-shop Polynesian tribal armbands declined post-2010 as artists and clients increasingly demand proper Polynesian protocol. Authentic tatau by Polynesian artists is the rising path.',
    'The Mauna Kea protests (2019) drove a noticeable wave of mountain-silhouette and "kapu aloha" symbolism among locals — a useful template for forecasting how local political moments translate into tattoo demand.',
  ],
  yearRange: { start: 1985, end: 2030 },
}

export const MUSIC_DATASET: IndustryDataset = {
  industry: {
    id: 'music',
    label: 'Music',
    blurb: 'Scaffold — drop genre curves to predict the next sonic revival.',
    status: 'scaffold',
  },
  styles: [],
  cycleNotes: [],
  yearRange: { start: 1960, end: 2030 },
}

export const INTERIOR_DATASET: IndustryDataset = {
  industry: {
    id: 'interior',
    label: 'Interior Design',
    blurb: 'Scaffold — add mid-century, brutalist, cottagecore strands here.',
    status: 'scaffold',
  },
  styles: [],
  cycleNotes: [],
  yearRange: { start: 1950, end: 2030 },
}

export const DATASETS: Record<string, IndustryDataset> = {
  tattoo: TATTOO_DATASET,
  fashion: FASHION_DATASET,
  walkin: WALKIN_DATASET,
  'hawaii-souvenir': HAWAII_DATASET,
  music: MUSIC_DATASET,
  interior: INTERIOR_DATASET,
}

export function getDataset(id: string): IndustryDataset {
  return DATASETS[id] ?? TATTOO_DATASET
}
