import type { IndustryDataset, StyleStrand } from './types'

const tattooStyles: StyleStrand[] = [
  {
    id: 'americana-traditional',
    label: 'Americana Traditional',
    tagline: 'Bold lines, limited palette, eternal',
    description:
      'Sailor Jerry, Bert Grimm, Ed Hardy lineage. Heavy black outlines, a tight palette of red/yellow/green/black, classic motifs (eagles, daggers, panthers, pin-ups). Built to age well across 40+ years on skin.',
    origin: 1900,
    ancestors: [],
    curve: [
      { year: 1920, value: 35 },
      { year: 1945, value: 78 },
      { year: 1960, value: 55 },
      { year: 1975, value: 30 },
      { year: 1990, value: 38 },
      { year: 2005, value: 70 },
      { year: 2015, value: 84 },
      { year: 2022, value: 88 },
      { year: 2025, value: 82 },
    ],
    signals: ['nostalgia', 'craft revival', 'analog backlash', 'durability bias'],
    tags: ['bold', 'iconographic', 'colored', 'heritage'],
    pioneers: ['Sailor Jerry Collins', 'Bert Grimm', 'Ed Hardy'],
  },
  {
    id: 'fine-line',
    label: 'Fine Line / Single Needle',
    tagline: 'Whisper-thin lines, micro detail',
    description:
      'Single-needle origins in 1970s East LA prison and Chicano scenes (Jack Rudy, Freddy Negrete, Charlie Cartwright at Good Time Charlie\'s). Resurfaced as celebrity-friendly micro tattoos around 2005, then exploded post-2017 with Dr. Woo and Instagram-native artists.',
    origin: 1970,
    parentId: 'black-grey-chicano',
    ancestors: ['black-grey-chicano'],
    curve: [
      { year: 1975, value: 42 },
      { year: 1985, value: 55 },
      { year: 1995, value: 28 },
      { year: 2005, value: 48 },
      { year: 2015, value: 70 },
      { year: 2020, value: 88 },
      { year: 2024, value: 95 },
      { year: 2025, value: 96 },
    ],
    signals: ['minimalism', 'instagram-native', 'celebrity adoption', 'micro detail'],
    tags: ['delicate', 'minimal', 'monochrome', 'modern'],
    pioneers: ['Jack Rudy', 'Freddy Negrete', 'Dr. Woo', 'JonBoy'],
  },
  {
    id: 'black-grey-chicano',
    label: 'Black & Grey Chicano',
    tagline: 'Photorealism in soft greys, smoky shading',
    description:
      'Born in 1970s LA from prison-yard single-needle work. Religious iconography, lowrider culture, smoke and roses. Bridge between fine line and full realism.',
    origin: 1970,
    ancestors: [],
    curve: [
      { year: 1975, value: 38 },
      { year: 1990, value: 65 },
      { year: 2005, value: 78 },
      { year: 2015, value: 68 },
      { year: 2022, value: 60 },
      { year: 2025, value: 64 },
    ],
    signals: ['heritage', 'realism', 'storytelling'],
    tags: ['monochrome', 'smoky', 'cultural'],
    pioneers: ['Mister Cartoon', 'Chuey Quintanar'],
  },
  {
    id: 'tribal',
    label: 'Tribal / Polynesian',
    tagline: 'Solid black geometry rooted in Oceania',
    description:
      'True Polynesian (Tatau, Marquesan, Samoan) is millennia old. Western "tribal" shorthand peaked in the 1990s post-grunge. Authentic Polynesian work has steadily climbed since 2010 alongside indigenous reclamation.',
    origin: 1980,
    ancestors: [],
    curve: [
      { year: 1990, value: 60 },
      { year: 1998, value: 92 },
      { year: 2005, value: 70 },
      { year: 2012, value: 30 },
      { year: 2018, value: 38 },
      { year: 2024, value: 52 },
      { year: 2025, value: 56 },
    ],
    signals: ['cultural reclamation', 'indigenous craft', 'bold shapes'],
    tags: ['blackwork', 'cultural', 'pattern'],
  },
  {
    id: 'realism',
    label: 'Photo Realism',
    tagline: 'Skin as a print, every pore rendered',
    description:
      'Emerged in the late 1990s with rotary machines and refined cartridges; matured around 2010 with hyperrealism. High-effort, high-skill style that competes with portraiture and oil painting.',
    origin: 1995,
    parentId: 'black-grey-chicano',
    ancestors: ['black-grey-chicano'],
    curve: [
      { year: 2000, value: 35 },
      { year: 2010, value: 70 },
      { year: 2017, value: 86 },
      { year: 2022, value: 78 },
      { year: 2025, value: 70 },
    ],
    signals: ['technical mastery', 'portrait commission', 'memorial'],
    tags: ['detailed', 'modern', 'monochrome'],
    pioneers: ['Nikko Hurtado', 'Bob Tyrrell'],
  },
  {
    id: 'hyperrealism',
    label: 'Hyperrealism',
    tagline: 'Skin-as-photography, every micro-shadow',
    description:
      'A 2010s extreme of realism — pushed by competition culture and Instagram zoom. Long sittings, color charts, airbrush-style gradients. Ages well only with a master; technically punishing.',
    origin: 2008,
    parentId: 'realism',
    ancestors: ['realism', 'black-grey-chicano'],
    curve: [
      { year: 2010, value: 35 },
      { year: 2016, value: 78 },
      { year: 2020, value: 82 },
      { year: 2024, value: 70 },
      { year: 2025, value: 64 },
    ],
    signals: ['competition culture', 'long sittings', 'technical mastery'],
    tags: ['detailed', 'monochrome', 'modern'],
  },
  {
    id: 'mandala',
    label: 'Mandala',
    tagline: 'Symmetric circular sacred geometry',
    description:
      'Subset of geometric/blackwork built on radial symmetry, rooted in Hindu/Buddhist iconography. Surged with the 2014 sacred-geometry wave; durable as a center-of-piece motif inside larger ornamental sleeves.',
    origin: 2012,
    parentId: 'geometric',
    ancestors: ['geometric', 'blackwork', 'dotwork'],
    curve: [
      { year: 2014, value: 55 },
      { year: 2018, value: 72 },
      { year: 2022, value: 60 },
      { year: 2025, value: 56 },
    ],
    signals: ['symmetry', 'spiritual', 'craft'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
  {
    id: 'micro-realism',
    label: 'Micro Realism',
    tagline: 'Realism shrunk to a coin',
    description:
      'Korean and Spanish scenes (Inal Bersekov, Eva Krbdk) compressed full realism into 2-inch panels with fine line outlines. Defined the late 2010s Instagram aesthetic of pets, flowers and tiny still lifes.',
    origin: 2014,
    parentId: 'fine-line',
    ancestors: ['fine-line', 'realism'],
    curve: [
      { year: 2016, value: 30 },
      { year: 2019, value: 65 },
      { year: 2022, value: 88 },
      { year: 2025, value: 86 },
    ],
    signals: ['instagram-native', 'collectible', 'small format'],
    tags: ['minimal', 'detailed', 'modern'],
    pioneers: ['Inal Bersekov', 'Eva Krbdk'],
  },
  {
    id: 'neo-traditional',
    label: 'Neo-Traditional',
    tagline: 'Traditional bones, painterly skin',
    description:
      'Expands Americana with deeper palettes, soft gradients, art nouveau line weights. Late-2000s wave (Jeff Gogue, Russ Abbott) into a steady mainstream presence.',
    origin: 2005,
    parentId: 'americana-traditional',
    ancestors: ['americana-traditional'],
    curve: [
      { year: 2008, value: 45 },
      { year: 2015, value: 78 },
      { year: 2020, value: 80 },
      { year: 2025, value: 72 },
    ],
    signals: ['painterly', 'palette expansion', 'illustrative'],
    tags: ['colored', 'illustrative', 'modern'],
  },
  {
    id: 'new-school',
    label: 'New School',
    tagline: 'Cartoonish, bulging, candy-colored',
    description:
      'Mid-1990s Skribblz / Marcus Pacheco era. Exaggerated proportions, 3D rendering, graffiti DNA. Faded after 2005, low-key revival forming in collaboration with cyber sigilism artists.',
    origin: 1990,
    parentId: 'americana-traditional',
    ancestors: ['americana-traditional'],
    curve: [
      { year: 1995, value: 55 },
      { year: 2002, value: 78 },
      { year: 2010, value: 35 },
      { year: 2020, value: 18 },
      { year: 2025, value: 26 },
    ],
    signals: ['cartoon revival', 'graffiti', 'maximalist color'],
    tags: ['colored', 'illustrative', 'maximal'],
  },
  {
    id: 'japanese-irezumi',
    label: 'Japanese Irezumi',
    tagline: 'Bodysuits, koi, dragons, wind bars',
    description:
      'Edo-period roots. Western adoption surged in the 1980s through Horiyoshi III and Don Ed Hardy. Steady, slow-burning popularity; never a fad, never the lead.',
    origin: 1700,
    ancestors: [],
    curve: [
      { year: 1985, value: 55 },
      { year: 2000, value: 60 },
      { year: 2015, value: 65 },
      { year: 2025, value: 60 },
    ],
    signals: ['heritage', 'large scale', 'narrative'],
    tags: ['colored', 'heritage', 'pattern'],
    pioneers: ['Horiyoshi III'],
  },
  {
    id: 'blackwork',
    label: 'Blackwork',
    tagline: 'Saturated black geometry and ornament',
    description:
      'Distinct from tribal; descends from European etching, mehndi, sacred geometry. Strongly tied to ornamental, mandala and dotwork. Steady riser since 2012.',
    origin: 2008,
    parentId: 'tribal',
    ancestors: ['tribal'],
    curve: [
      { year: 2012, value: 40 },
      { year: 2018, value: 70 },
      { year: 2022, value: 78 },
      { year: 2025, value: 74 },
    ],
    signals: ['ornament', 'sacred geometry', 'monochrome maximalism'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
  {
    id: 'dotwork',
    label: 'Dotwork / Stippling',
    tagline: 'Tonal shading made of dots',
    description:
      'Xed LeHead-era dotwork from the 1990s Berlin scene. Used as a shading vocabulary inside ornamental and geometric. Rarely the headline, often the substrate.',
    origin: 1992,
    ancestors: [],
    curve: [
      { year: 1998, value: 30 },
      { year: 2010, value: 55 },
      { year: 2018, value: 70 },
      { year: 2025, value: 64 },
    ],
    signals: ['craft', 'patience', 'texture'],
    tags: ['blackwork', 'pattern'],
  },
  {
    id: 'geometric',
    label: 'Geometric',
    tagline: 'Sacred geometry, ruler-true lines',
    description:
      'Mandala and sacred geometry boom around 2013, often paired with dotwork or fine line. Now a substyle backbone for ornamental and cyber sigilism.',
    origin: 2010,
    parentId: 'blackwork',
    ancestors: ['dotwork', 'blackwork'],
    curve: [
      { year: 2013, value: 55 },
      { year: 2018, value: 78 },
      { year: 2022, value: 70 },
      { year: 2025, value: 62 },
    ],
    signals: ['symmetry', 'meditation', 'craft'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
  {
    id: 'watercolor',
    label: 'Watercolor',
    tagline: 'Splashes, drips, no outlines',
    description:
      'Early-2010s viral aesthetic (Ondrash). Aged poorly; popularity peaked then fell as collectors saw 5-year results. Lives on as an accent inside neo-traditional.',
    origin: 2010,
    parentId: 'neo-traditional',
    ancestors: ['neo-traditional'],
    curve: [
      { year: 2013, value: 70 },
      { year: 2017, value: 78 },
      { year: 2021, value: 45 },
      { year: 2025, value: 28 },
    ],
    signals: ['painterly', 'no outline', 'pinterest era'],
    tags: ['colored', 'illustrative'],
  },
  {
    id: 'trash-polka',
    label: 'Trash Polka',
    tagline: 'Red and black collage chaos',
    description:
      'Buena Vista Tattoo Club, Germany. Early 2010s peak. Photorealism + brushstrokes + typographic noise.',
    origin: 2008,
    parentId: 'realism',
    ancestors: ['realism'],
    curve: [
      { year: 2012, value: 60 },
      { year: 2016, value: 70 },
      { year: 2022, value: 32 },
      { year: 2025, value: 24 },
    ],
    signals: ['collage', 'editorial', 'bold contrast'],
    tags: ['colored', 'maximal', 'modern'],
  },
  {
    id: 'cyber-sigilism',
    label: 'Cyber Sigilism',
    tagline: 'Y2K chrome meets occult linework',
    description:
      'A 2020+ TikTok-fueled fusion: tribal silhouettes, fine line execution, sigil and Y2K typography. Compresses the canonical 22-year cycle to ~4 years end-to-end.',
    origin: 2020,
    parentId: 'blackwork',
    ancestors: ['fine-line', 'tribal', 'blackwork'],
    curve: [
      { year: 2021, value: 28 },
      { year: 2023, value: 70 },
      { year: 2025, value: 88 },
    ],
    signals: ['tiktok-native', 'y2k revival', 'gen-z occult', 'fast cycle'],
    tags: ['blackwork', 'pattern', 'modern', 'fusion'],
  },
  {
    id: 'illustrative-anime',
    label: 'Illustrative / Anime',
    tagline: 'Manga lineart, cel shading',
    description:
      'Driven by post-2018 anime mainstreaming. Big in Asia and Latin America. Often colored, often single-panel comp.',
    origin: 2015,
    parentId: 'new-school',
    ancestors: ['new-school', 'neo-traditional'],
    curve: [
      { year: 2018, value: 40 },
      { year: 2022, value: 70 },
      { year: 2025, value: 78 },
    ],
    signals: ['fandom', 'streaming', 'illustration'],
    tags: ['colored', 'illustrative', 'modern'],
  },
  {
    id: 'ignorant-handpoke',
    label: 'Ignorant / Handpoke',
    tagline: 'Wonky lines, deliberate amateurism',
    description:
      'Fuzi Uvtpk-led 2010s scene; handpoke made it portable. Reads as anti-craft but is a craft of its own. Pairs with fine line on a single sleeve.',
    origin: 2009,
    ancestors: [],
    curve: [
      { year: 2012, value: 35 },
      { year: 2018, value: 62 },
      { year: 2022, value: 70 },
      { year: 2025, value: 64 },
    ],
    signals: ['anti-craft', 'punk', 'flash culture'],
    tags: ['minimal', 'illustrative', 'modern'],
  },
  {
    id: 'ornamental',
    label: 'Ornamental',
    tagline: 'Lace, jewelry, body-as-frame',
    description:
      'Decorative blackwork descended from mehndi and Eastern European ornament. Used as clothing-line work that follows anatomy.',
    origin: 2014,
    parentId: 'blackwork',
    ancestors: ['blackwork', 'dotwork'],
    curve: [
      { year: 2016, value: 45 },
      { year: 2020, value: 70 },
      { year: 2024, value: 80 },
      { year: 2025, value: 78 },
    ],
    signals: ['anatomical', 'craft', 'feminine maximalism'],
    tags: ['blackwork', 'pattern', 'modern'],
  },
]

export const TATTOO_DATASET: IndustryDataset = {
  industry: {
    id: 'tattoo',
    label: 'Tattoo',
    blurb: 'Cycle window 18-25 years, compressing toward 6-10 since 2017.',
    status: 'active',
  },
  styles: tattooStyles,
  cycleNotes: [
    'Sailor Jerry Americana peaked ~1945, dipped, came back hard ~2005 and has held the lead among under-30 collectors for two decades.',
    'Fine line shows two distinct waves: 1975-1985 East LA single-needle, then a Dr. Woo / Instagram explosion 2017-now.',
    'Tribal sat dormant ~2008-2018 then re-emerged as cyber sigilism — a clear "fusion-driven" comeback rather than a faithful one.',
    'Watercolor is a textbook accelerated cycle: 7-year peak-to-trough vs the canonical 22, killed by visible aging.',
  ],
  yearRange: { start: 1900, end: 2030 },
}

export const FASHION_DATASET: IndustryDataset = {
  industry: {
    id: 'fashion',
    label: 'Fashion',
    blurb: 'Cycle window 20-25 years for silhouettes, 5-7 years for microtrends post-2010.',
    status: 'active',
  },
  styles: [
    {
      id: 'mod-60s',
      label: 'Mod (60s)',
      tagline: 'A-line minis, monochrome, geometric prints',
      description:
        'British 1960s — Mary Quant, Twiggy, Carnaby Street. Geometric prints, A-line shifts, knee-high boots. Hedi Slimane echoes ~2005, returned as a microtrend in 2024 with the "indie sleaze 2.0" wave.',
      origin: 1960,
      ancestors: [],
      curve: [
        { year: 1965, value: 92 },
        { year: 1972, value: 35 },
        { year: 1985, value: 22 },
        { year: 2005, value: 60 },
        { year: 2018, value: 32 },
        { year: 2024, value: 52 },
        { year: 2025, value: 55 },
      ],
      signals: ['silhouette', 'geometric', 'pop'],
      tags: ['silhouette', 'graphic'],
      pioneers: ['Mary Quant', 'André Courrèges', 'Twiggy'],
    },
    {
      id: 'hippie-bohemian',
      label: 'Hippie / Bohemian',
      tagline: 'Earth tones, fringe, peasant blouses, prairie',
      description:
        'Late-60s counterculture and 70s prairie. Flowy cotton, earth tones, ethnic textiles. The 2014 boho-festival wave (Coachella era) revived it; "cottagecore" 2020-22 is the descendant.',
      origin: 1967,
      ancestors: [],
      curve: [
        { year: 1971, value: 88 },
        { year: 1980, value: 28 },
        { year: 1995, value: 42 },
        { year: 2005, value: 55 },
        { year: 2014, value: 78 },
        { year: 2022, value: 60 },
        { year: 2025, value: 52 },
      ],
      signals: ['nostalgia', 'craft', 'earth tones', 'pinterest era'],
      tags: ['silhouette', 'soft', 'natural'],
    },
    {
      id: 'bell-bottoms',
      label: 'Bell Bottoms',
      tagline: 'Flared denim, hip-hugger waist',
      description:
        '1970s flared denim peak; late-1990s mainstream revival driven by Britney/JNCO; low-rise flare wave 2022-now. The classic 22-year cycle reference case.',
      origin: 1965,
      parentId: 'hippie-bohemian',
      ancestors: ['hippie-bohemian'],
      curve: [
        { year: 1972, value: 90 },
        { year: 1980, value: 25 },
        { year: 1998, value: 80 },
        { year: 2005, value: 35 },
        { year: 2018, value: 22 },
        { year: 2022, value: 68 },
        { year: 2025, value: 78 },
      ],
      signals: ['silhouette', 'denim', 'nostalgia'],
      tags: ['silhouette', 'denim'],
    },
    {
      id: 'disco-glam',
      label: 'Disco Glam',
      tagline: 'Sequins, jumpsuits, satin, Studio 54',
      description:
        '1977-79 peak; lampooned in the 80s, briefly fashionable around 2000 and again with the 2022 "Y2K disco" microtrend (Beyoncé Renaissance era).',
      origin: 1975,
      ancestors: [],
      curve: [
        { year: 1978, value: 88 },
        { year: 1985, value: 22 },
        { year: 2000, value: 48 },
        { year: 2010, value: 25 },
        { year: 2022, value: 62 },
        { year: 2025, value: 50 },
      ],
      signals: ['nightlife', 'shimmer', 'maximalism'],
      tags: ['glam', 'evening', 'maximal'],
    },
    {
      id: 'punk',
      label: 'Punk',
      tagline: 'Leather, plaid, safety pins, DIY',
      description:
        'Late-70s London (Westwood/McLaren) and NYC (Ramones). Mainstreamed via Vivienne Westwood through the 80s and 90s. Lives on as an evergreen subculture and as a recurring runway pull (Balenciaga 2022, McQueen archive references).',
      origin: 1976,
      ancestors: [],
      curve: [
        { year: 1979, value: 65 },
        { year: 1990, value: 45 },
        { year: 2005, value: 55 },
        { year: 2015, value: 40 },
        { year: 2022, value: 58 },
        { year: 2025, value: 50 },
      ],
      signals: ['anti-fashion', 'subculture', 'DIY'],
      tags: ['edgy', 'subculture'],
      pioneers: ['Vivienne Westwood', 'Malcolm McLaren'],
    },
    {
      id: 'power-suit-80s',
      label: '80s Power Suit',
      tagline: 'Shoulder pads, double-breasted, monochrome bold',
      description:
        'Reagan-era corporate power dressing. Returned 2017-19 (Mango / Zara wave), again 2022 with "office siren" / Saint Laurent silhouettes. Shoulder pads remain divisive.',
      origin: 1982,
      ancestors: [],
      curve: [
        { year: 1986, value: 86 },
        { year: 1993, value: 25 },
        { year: 2010, value: 18 },
        { year: 2018, value: 55 },
        { year: 2024, value: 48 },
        { year: 2025, value: 44 },
      ],
      signals: ['corporate', 'silhouette', 'authority'],
      tags: ['silhouette', 'tailoring', 'workwear'],
    },
    {
      id: 'preppy',
      label: 'Preppy',
      tagline: 'Polo collars, loafers, pastel layering',
      description:
        '80s Reagan-era prep (Ralph Lauren). Mid-2000s "Gossip Girl" revival. "Old money" / "tomato girl" 2023+ is the same DNA reframed.',
      origin: 1980,
      ancestors: [],
      curve: [
        { year: 1985, value: 68 },
        { year: 1995, value: 35 },
        { year: 2008, value: 65 },
        { year: 2016, value: 38 },
        { year: 2023, value: 70 },
        { year: 2025, value: 75 },
      ],
      signals: ['heritage', 'aspirational', 'classic'],
      tags: ['classic', 'tailoring'],
    },
    {
      id: 'grunge',
      label: 'Grunge',
      tagline: 'Plaid flannels, slip dresses, combat boots',
      description:
        'Seattle 1991-94 (Nirvana, Marc Jacobs for Perry Ellis). 2014-16 Hedi-at-Saint-Laurent revival. "Grunge revival" microtrend re-emerged 2022 with cyber-sigilism crossover.',
      origin: 1990,
      ancestors: [],
      curve: [
        { year: 1993, value: 82 },
        { year: 1999, value: 30 },
        { year: 2014, value: 65 },
        { year: 2018, value: 40 },
        { year: 2022, value: 58 },
        { year: 2025, value: 52 },
      ],
      signals: ['anti-fashion', 'subculture', 'thrift'],
      tags: ['subculture', 'thrift', 'denim'],
    },
    {
      id: 'y2k',
      label: 'Y2K',
      tagline: 'Low-rise, butterfly motifs, baby tees, chrome',
      description:
        '1999-2003 — Britney/Aaliyah/Destiny\'s Child era. Tech-optimist chrome, butterfly motifs, low-rise denim. The flagship case for compressed cycles: 18-year gap to 2020 TikTok revival, ongoing as of 2025.',
      origin: 1998,
      ancestors: [],
      curve: [
        { year: 2001, value: 88 },
        { year: 2008, value: 25 },
        { year: 2015, value: 18 },
        { year: 2020, value: 60 },
        { year: 2023, value: 90 },
        { year: 2025, value: 88 },
      ],
      signals: ['tiktok-native', 'nostalgia', 'gen-z'],
      tags: ['nostalgic', 'graphic', 'denim'],
    },
    {
      id: 'low-rise',
      label: 'Low-Rise Denim',
      tagline: 'Hip-skimming waistbands, visible belt',
      description:
        'Y2K substyle: 2001-05 peak, declared dead 2007, returned 2022 with TikTok-Gen-Z. Trades places with high-waist as the dominant denim silhouette every ~15-20 years.',
      origin: 2000,
      parentId: 'y2k',
      ancestors: ['y2k', 'bell-bottoms'],
      curve: [
        { year: 2003, value: 90 },
        { year: 2008, value: 35 },
        { year: 2015, value: 12 },
        { year: 2022, value: 65 },
        { year: 2025, value: 80 },
      ],
      signals: ['tiktok-native', 'silhouette', 'denim'],
      tags: ['silhouette', 'denim', 'nostalgic'],
    },
    {
      id: 'indie-sleaze',
      label: 'Indie Sleaze',
      tagline: 'Flash photography, American Apparel, neon, party',
      description:
        '2006-12 NYC/Cobrasnake era — overexposed flash, Cory Kennedy, MGMT. Declared a comeback in 2022 by trend forecasters; partial revival, weaker than Y2K.',
      origin: 2006,
      ancestors: [],
      curve: [
        { year: 2008, value: 70 },
        { year: 2013, value: 28 },
        { year: 2018, value: 12 },
        { year: 2022, value: 48 },
        { year: 2025, value: 55 },
      ],
      signals: ['nightlife', 'tiktok-native', 'pinterest era'],
      tags: ['subculture', 'nostalgic'],
    },
    {
      id: 'athleisure',
      label: 'Athleisure',
      tagline: 'Leggings, hoodies, performance fabrics worn out of context',
      description:
        'Lululemon/Athleta wave 2010-16. Quietly absorbed into mainstream wardrobe; no longer a "trend" but a baseline. Gorpcore is the current outdoor-leaning descendant.',
      origin: 2009,
      ancestors: [],
      curve: [
        { year: 2014, value: 78 },
        { year: 2018, value: 70 },
        { year: 2022, value: 58 },
        { year: 2025, value: 52 },
      ],
      signals: ['performance', 'comfort', 'mainstream'],
      tags: ['casual', 'performance'],
    },
    {
      id: 'gorpcore',
      label: 'Gorpcore',
      tagline: 'Technical outerwear, hiking shoes, urban outdoor',
      description:
        'Salomon, Arc\'teryx, Patagonia worn in cities. Emerged 2017, mainstream by 2021 (Hoka craze, Salomon XT-6). Currently saturating; quiet luxury threatens replacement.',
      origin: 2017,
      parentId: 'athleisure',
      ancestors: ['athleisure'],
      curve: [
        { year: 2019, value: 45 },
        { year: 2022, value: 75 },
        { year: 2024, value: 82 },
        { year: 2025, value: 78 },
      ],
      signals: ['technical', 'streetwear', 'tiktok-native'],
      tags: ['casual', 'performance', 'modern'],
    },
    {
      id: 'balletcore',
      label: 'Balletcore',
      tagline: 'Pointe-shoe pinks, leotards, leg warmers, tulle',
      description:
        'Late 2022 microtrend out of "soft girl" / Sofia Coppola visual cluster. Compressed peak — saturated within 18 months. Lives on inside coquette.',
      origin: 2022,
      ancestors: [],
      curve: [
        { year: 2022, value: 35 },
        { year: 2023, value: 78 },
        { year: 2024, value: 60 },
        { year: 2025, value: 45 },
      ],
      signals: ['tiktok-native', 'soft girl', 'fast cycle'],
      tags: ['feminine', 'soft', 'modern'],
    },
    {
      id: 'coquette',
      label: 'Coquette',
      tagline: 'Bows, ribbons, lace, Lolita-adjacent',
      description:
        'Tumblr-rooted feminine maximalism (~2014-15) reborn on TikTok 2022+. Bow-on-everything aesthetic. Overlap with balletcore but more decorative.',
      origin: 2014,
      ancestors: ['balletcore'],
      curve: [
        { year: 2016, value: 35 },
        { year: 2020, value: 22 },
        { year: 2023, value: 75 },
        { year: 2024, value: 80 },
        { year: 2025, value: 70 },
      ],
      signals: ['tiktok-native', 'soft girl', 'maximal feminine'],
      tags: ['feminine', 'maximal', 'modern'],
    },
    {
      id: 'quiet-luxury',
      label: 'Quiet Luxury / Old Money',
      tagline: 'Logo-free, neutral palette, knit polos, Loro Piana',
      description:
        'Backlash to logo-mania and gorpcore loudness. Succession-fueled (Tom Wambsgans, Kendall Roy). The Row, Brunello Cucinelli. Strong correlate of late-cycle economic uncertainty — same DNA as 1990s minimalism.',
      origin: 2022,
      parentId: 'preppy',
      ancestors: ['preppy'],
      curve: [
        { year: 2022, value: 35 },
        { year: 2023, value: 70 },
        { year: 2024, value: 88 },
        { year: 2025, value: 82 },
      ],
      signals: ['anti-logo', 'aspirational', 'tiktok-native'],
      tags: ['classic', 'modern', 'luxury'],
    },
    {
      id: 'minimalism-90s',
      label: '90s Minimalism',
      tagline: 'Slip dresses, square necks, restraint, Helmut Lang',
      description:
        'Calvin Klein / Helmut Lang / Jil Sander 1993-99. The aesthetic ancestor of quiet luxury. Microtrend revivals 2014, 2024.',
      origin: 1993,
      ancestors: [],
      curve: [
        { year: 1996, value: 75 },
        { year: 2002, value: 28 },
        { year: 2014, value: 55 },
        { year: 2018, value: 35 },
        { year: 2024, value: 60 },
        { year: 2025, value: 65 },
      ],
      signals: ['restraint', 'craft', 'anti-logo'],
      tags: ['classic', 'minimal'],
      pioneers: ['Helmut Lang', 'Jil Sander', 'Calvin Klein'],
    },
  ],
  cycleNotes: [
    'Bell bottoms (1972 peak) returned ~1998, then again ~2022 — almost exactly the canonical 22-year cycle, twice in a row.',
    'Y2K compresses the cycle: 18-year gap from 2003 peak to 2021 mainstream return (TikTok era), and the revival is now larger than the original.',
    'Quiet luxury 2023+ is the textbook backlash trend: a counter-reaction to gorpcore loudness and logo-mania, mapping the same DNA as 1990s minimalism.',
    'Balletcore is a clean accelerated-cycle case: trough → peak → fade in under 24 months, vs the canonical 22.',
    'Preppy / old money has now had three distinct waves (1985, 2008, 2023) — closer to a 15-year cycle than a 22-year one in this category.',
  ],
  yearRange: { start: 1955, end: 2030 },
}

export const MUSIC_DATASET: IndustryDataset = {
  industry: {
    id: 'music',
    label: 'Music',
    blurb: 'Scaffold — drop genre curves to predict the next sonic revival.',
    status: 'scaffold',
  },
  styles: [],
  cycleNotes: [],
  yearRange: { start: 1960, end: 2030 },
}

export const INTERIOR_DATASET: IndustryDataset = {
  industry: {
    id: 'interior',
    label: 'Interior Design',
    blurb: 'Scaffold — add mid-century, brutalist, cottagecore strands here.',
    status: 'scaffold',
  },
  styles: [],
  cycleNotes: [],
  yearRange: { start: 1950, end: 2030 },
}

export const DATASETS: Record<string, IndustryDataset> = {
  tattoo: TATTOO_DATASET,
  fashion: FASHION_DATASET,
  music: MUSIC_DATASET,
  interior: INTERIOR_DATASET,
}

export function getDataset(id: string): IndustryDataset {
  return DATASETS[id] ?? TATTOO_DATASET
}
